version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    volumes:
      - ./data:/data
      - ./template/ressource/images:/app/template/ressource/images

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-available/default:/etc/nginx/sites-enabled/default
      - ./permsHttps/selfsigned.crt:/etc/nginx/ssl/selfsigned.crt
      - ./permsHttps/selfsigned.key:/etc/nginx/ssl/selfsigned.key
    depends_on:
      - app

volumes:
  certbot-etc:
  certbot-www:
